### ISSUE TITLE
Wrong encoding for titles in cyrillic

### ISSUE THREAD

**Issue by hristov296** [synzen/Discord.RSS#151]
**Describe the bug**
The title of the new post appears with the wrong encoding, if it is in cyrrilic

**To Reproduce**
1. Subscribe to an rss, which is in a cyrrilic language.(for example `~rssadd https://www.novinite.bg/rss.php`)
2. Upon receiving new post, it will appear wrongly encoded.

**Screenshots**
![image](https://user-images.githubusercontent.com/18082688/76744727-6158bd80-677d-11ea-93bf-e91370ad474f.png)

**Branch (please specify one):**
public bot

**Additional context**
I could try implement a fix, if someone can point me to the correct file

**Comment by synzen** [comment]
Thanks for the report. Please specify the branch as required on the Issue Template:

**Branch (please specify one):**
master, dev, or public bot

Given that you used `~rssadd`, I'm guessing that you are either on master or the public bot

**Comment by hristov296** [comment]
Ah sorry, yes it's the public bot. I just added it to my server, didn't clone from github.

**Comment by synzen** [comment]
The feed should properly show now on the public bot:
![image](https://user-images.githubusercontent.com/18688793/76814845-4f553a00-67d2-11ea-858d-0e7d708d1ab1.png)

For the record, if self hosting, this is done by adding to the `config.feeds.decode` - the URL is the key, and the encoding is the value. Otherwise the bot owner must specify the encoding for any relevant feeds
