### ISSUE TITLE
[Feature Request] Better Error Responses for "restore" command 

### ISSUE THREAD

**Issue by mriise** [synzen/Discord.RSS#153]
the `restore` command hasn't had the best error messages or help for using it. 

If a guild is being attempted to be restored but hasn't been added into a server, it only replies with 
`Cannot read property 'send' of undefined` which isn't the most helpful for understanding what's wrong. Yes, I was stupid for not realizing it earlier, but the message wasn't helpful.

On a side note, the command doesn't have a great explanation in general, I've wasted quite a few hours figuring out how to properly use the command with the JSON attachment the way it wants. A menu stepping through the restore (like `rssmention` or whatever) process or a bit more explanation on the wiki would be nice.

**Comment by synzen** [comment]
Thanks for the feedback, apologies for the frustration. The error you encountered was because of a typo on my end, causing it to send the runtime error rather than the intended user-friendly error which was `Unable to restore server, ID ${id} was not found in cache.`. This has been fixed now in the latest master commit, or release 5.0.5. 

I've also further emphasized on the wiki that the JSON file must be uploaded alongside the command - hopefully this will cause less confusion.

**Comment by mriise** [comment]
thanks!
