### ISSUE TITLE
Support creation of the Custom Placeholders in either Commands or Web

### ISSUE THREAD

**Issue by mriise** [synzen/Discord.RSS#158]
The wiki mentions the capabilities of custom RegEx Ops but there is no way of users to take advantage of this without downloading the JSON as a backup and asking for a restore. 

If this feature isn't to be worked on soon or isn't already being done in v6- I might be interested in submitting a PR for the web client that adds this feature.

**Comment by synzen** [comment]
Users are intentionally disallowed from directly inputting regex because of the inherent dangers of [ReDoS](https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS).

Because of this, there was never any reason to implement it in commands (it is not trivial to add a command for this - and commands are on the way to being rewritten anyways), nor in the control panel (meant for regular users). If there was a bot admin section on the web, sure, but that itself is a whole other beast.

Thanks for the suggestion though.

**Comment by mriise** [comment]
got it, thanks!
