### ISSUE TITLE
Unicode isn't supported

### ISSUE THREAD

**Issue by Minaru** [synzen/Discord.RSS#27]
Hello,

I noticed on some of the RSS feeds i'm following that some symbols out of the ASCII scope doesn't display properly. Here is in example below: 

![capture](https://user-images.githubusercontent.com/17097702/32047818-75a00aea-ba47-11e7-8f9f-32070a086b2b.PNG)

This error occurs both on windows and linux desktop apps.

If you're currently too busy to deal with this issue, please feel free to indicate me which files i should look into where RSS feeds are retrieved, formatted and finally posted in server's channels, so i can make a pull request fixing this.

**Comment by synzen** [comment]
Looks like [iconv-lite](https://www.npmjs.com/package/iconv-lite) is the culprit, which is what [needle](https://www.npmjs.com/package/needle) uses, You can see the difference:

```js
require('needle').get('https://www.cert.ssi.gouv.fr/feed/', function(err, res) {
  console.log(res.body) // "needle"'s request
  // snippet: ont Ã©tÃ© dÃ©couvertes dans
})
```
```js
require('needle').get('https://www.cert.ssi.gouv.fr/feed/', { decode: false }, function(err, res) {
  console.log(res.body) // "needle"'s request
  // snippet: ont été découvertes dans
})
```

I worked hard through rigorous tests to find the best request module for D.RSS, and `needle` seemed like the best one for speed/reliability. Seeing that this is an issue however, I have to figure out a fix or find an alternative as a last resort since this is unfamiliar territory for me, so it might take me a while to find the time for this, unless someone else gets to it first. I'll leave it open for now until I get this sorted

**Comment by Minaru** [comment]
If `{ decode: false }` is what fixes the problem, why not using it in rss/request.js?

(lines 5 to 11 in rss/request.jss)
```
  const options = {
    timeout: 30000,
    read_timeout: 27000,
    follow_max: 5,
    follow_set_cookies: true,
    rejectUnauthorized: true,
    decode: false
}
```

Would it break something else if we would start using this needle response option?

**Comment by synzen** [comment]
That is what I don't know, because this is unfamiliar territory. I have however added this option to the public bot to see if anyone complains about anything, and if there are no complaints after a bit of time, then I guess it's fine

**Comment by Minaru** [comment]
Thanks!

I will try to update my own self-hosted version asap with this line and will keep you up to date about any changes or bugs i might notice too then. I might run tests too with stuff like cyrilic alphabet, Japanese/Chinese characters and smileys to post a before/after here if i have some time before we see there is no problem with this change.

Don't hesitate to contact me if you need help on the bot btw

**Comment by synzen** [comment]
Looks like everything's ok.

**Comment by Minaru** [comment]
Didn't have time with pro life to check out other special characters.
As for my own language, characters like "éèëêïîçà" are correctly displaying too.
