### ISSUE TITLE
Can't get Images from RSS feed

### ISSUE THREAD

**Issue by Bewinxed** [synzen/Discord.RSS#5]
Hello, Lovely bot thanks for your work

I got it set up and working but i can't seem to be able to get any images from the RSS feed

this is the feed : feeds.feedburner.com/surrenderat20/CqWw

I even tried setting the message to:

`{image1} {image2} {image3} {image4} {image5} {image6} {image7} {image8} {image9} {image10} {image11} {image12} {image13} {image14}`

And it brings up nothing.

The URL brings only the thumbnail of the site's logo.

**Comment by synzen** [comment]
Well first of all, any and all images are identified by rsstest so if none were identified, adding them in will literally not do anything (and the maximum is `image9` as well)

That being said, I found the issue, thank you, and have fixed it. You should now be getting two image links for every article in that feed. However, if what you're looking for is one of those numerous images you see in the feed and not any of the image links found by rsstest, then those images cannot be retrieved because the author of the feed put those images in the description of the feed. Here is a snapshot of the raw description for a random article:

![article descrip](http://i.imgur.com/VUBzgZ1.png)

For the purposes of Discord.RSS, they can't be retrieved because they are not in any of the article's actual properties. Images in the description aren't intended to be delivered as a property of RSS feeds, especially when being sent to Discord.

**Comment by Bewinxed** [comment]
Thank you for your help :) prob is this feed in particular first 2 images are like 72px versions of the big one, but i appreciate your help.
