### ISSUE TITLE
Move config.json out of repo for straightforward upgrades

### ISSUE THREAD

**Issue by Danpiel** [synzen/Discord.RSS#54]
This is minor issue, but manual backup of config every time consumes time, instead I suggest moving config.json to config.json.template, and copy it for usage.

For future upgrades compare it with `git diff --no-index -- config.json config.json.template` to see the difference

**Comment by Macley-Kun** [comment]
@synzen any comment on this?
Honestly i'm used config.json.example format myself.

**Comment by synzen** [comment]
tbh I don't quite like the idea since it adds more steps/complication to the setup process - something that I would very much like to keep as simple as possible (the number of steps already got [larger](https://github.com/synzen/Discord.RSS/wiki/Setup) on dev branch which I didn't like). It's definitely an issue if you update frequently, however no one is obligated to update on every commit unless it's absolutely critical (something I'd make clear for sure)

**Comment by Danpiel** [comment]
Initially it's ok, removes the step `cd /opt/discord.rss/ && cp config.template config.json`
, but later I cannot `git pull` for fast update. I need manually to copy config out to avoid override with checkout.

Or support additional file for configuration, config.json stays as default, and second config works like override.
