### ISSUE TITLE
UTF8-Support for german letters (Ö, Ä, Ü)

### ISSUE THREAD

**Issue by CloudMaker97** [synzen/Discord.RSS#63]
The bot can't handle the UTF8 Charset, a expression from a result was:
POL-HB: Nr.:0522 --Fl�chtiger Tankstellenr�uber--

But has to be
POL-HB: Nr.:0522 --Flüchtiger Tankstellenräuber--

The correct conversion has to be provided.

**Comment by synzen** [comment]
I just copy pasted the phrase " POL-HB: Nr.:0522 --Flüchtiger Tankstellenräuber--" into the title of an article for a test feed and it came out fine in Discord:


![image](https://user-images.githubusercontent.com/18688793/44283781-6ebe6680-a22d-11e8-80bb-66f2018acc77.png)


Otherwise please provide a feed to work with
